### ISSUE TITLE
lesson3. Summarization

### ISSUE THREAD

**Issue by milkina** [YehorSurkov/homework#1]
1. Вынесите в отдельный метод, который будет вызываться два раза:
System.out.print("Input val1 : ");
        if (scX.hasNextInt()) {
            int x = scX.nextInt();
            } else {
                System.out.println(" System Error! ");
            }
2. То же самое для класса TheLowest

**Comment by YehorSurkov** [comment]
Готово.

**Comment by milkina** [comment]
Done
но вместо
 if (cycle == true) можно  if (cycle)

**Comment by YehorSurkov** [comment]
А тут что доделать?

**Comment by milkina** [comment]
вместо
if (cycle == true) можно if (cycle)

**Comment by YehorSurkov** [comment]
Готово. + 9 урок.
