### ISSUE TITLE
Car

### ISSUE THREAD

**Issue by milkina** [YehorSurkov/homework#10]
1. Lorry, SportCar - сначала пишите переменные потом конструктор
2. Создайте объекты класса Car, Lorry, SportCar. вызовите их методы
3. Driver должен расширять Person.

**Comment by YehorSurkov** [comment]
1 Готово
2 Готово. класс CarDemo.
3 Готово. Что-то на этом месте я действительно перегрелся при определении, а кто же чьё подмножество. Для Person есть одна переменная - полное имя, а для класса Driver - это две разные, т.ч. в конструкторе выкручивался.
