### ISSUE TITLE
Фрукты

### ISSUE THREAD

**Issue by milkina** [YehorSurkov/homework#13]
1.  Fruit.printManufacturer - Добавить мод. доступа.
2. costPerUnitOfWeight - можно сделать статическим
3. greenGrocery - класс с большой буквы

**Comment by YehorSurkov** [comment]
1) готово
2) готово
3)готово
4)уроки 10-11 готово

**Comment by milkina** [comment]
1. costPerUnitWeight перепишите большими буквами, раз это теперь константа
2.   final public void printManufacturer() - лучше сначала писать модификатор:
   public  final void printManufacturer()

**Comment by YehorSurkov** [comment]
Готово. А константы можно изменять? К ним геттеры и сеттеры пишутся?

**Comment by milkina** [comment]
Егор, но это же константы, их менять нельзя. Они пишутся  со словом final.
COSTPERUNITWEIGHT - для разделения слов используются подчеркивания. Например COST_PER_UNIT_WEIGHT

Done
