### ISSUE TITLE
Одежда

### ISSUE THREAD

**Issue by milkina** [YehorSurkov/homework#15]
1.  Clothes - переменную size сделайте типа Sizes
2.  ManClothes, WomanClothes - public abstract  для методов интерфейсов писать не обязательно
3.  Добавить equals, toString классам.
4. А это - Создать класс Ателье, содержащий методы одетьЖенщину, одетьМужчину, на вход которых будет поступать массив, содержащий все типы одежды. Метод одетьЖенщину выводит на консоль всю информацию о женской одежде. То же самое для метода одетьМужчину.

**Comment by YehorSurkov** [comment]
Всё, вроде, готово.

**Comment by milkina** [comment]
2. ManClothes, WomanClothes - public abstract для методов интерфейсов писать не обязательно.

**Comment by milkina** [comment]
Ставлю  done. Исправите.
