### ISSUE TITLE
StringBuilder

### ISSUE THREAD

**Issue by milkina** [YehorSurkov/homework#18]
Вместо
` sB[0].append(i1 + "+" + i2 + "=" + (i1 + i2));`
лучше писать 
` sB[0].append(i1).append("+").append(i2).append( "=").append(i1 + i2));`

Каждый раз когда вы используете +, создается новый объект 
String. Это как раз то чего мы пытаемся избежать, используя StringBuilder.

Компилятор вроде как оптимизирован, чтобы исправить это. Но я не уверена что во всех случаях.

**Comment by YehorSurkov** [comment]
1)Да, переделал, где увидел, это действительно важно. Я подозревал, что как и с выделением операции инкремент - декремент, с точки зрения памяти var++; и var += 1 (var = var + 1); -вещи довольно разные. (Хотя с современным развитием харда, думаю в подавляющем большинстве случаев это 1) устраняется компилятором, 2) не представляет затруднений.

2) 12 урок доделал. Хотя кажется, что к последним заданиям у меня начался перебор с массивами строк. Но я не совсем ещё понял механику работы Matcher-a: где он сам перебирает и можно сразу ставить условиt, а где ему нужно помочь с перебором.

 3)Задание с Person.toString через форматирование сделал для Employee.
