### ISSUE TITLE
lesson4.ChristmasGarland

### ISSUE THREAD

**Issue by milkina** [YehorSurkov/homework#2]
1.  Метод blinker - переменную j можно не вводить
2. Метод checkFirstSwitched -
 if ((first & 1) == 1) - избыточные круглые скобки. Можно просто -
 if (first & 1 == 1).
В остальных заданиях тоже исправьте.

**Comment by YehorSurkov** [comment]
![image](https://user-images.githubusercontent.com/34401787/34338355-9274592a-e970-11e7-8ac4-9c1d03eb5fbd.png)

**Comment by YehorSurkov** [comment]
Моя Идея говорит, что приоритет сравнения выше, чем у энда. Это к скобкам.

**Comment by milkina** [comment]
Да, согласна - была не права.
