### ISSUE TITLE
CalendarDemo

### ISSUE THREAD

**Issue by milkina** [YehorSurkov/homework#22]
1. Такой конструктор Date является deprecated. Используйте Calendar, например.
2. Вместо   System.out.println(myBirthday.get(**myBirthday**.DAY_OF_WEEK)); лучше   System.out.println(myBirthday.get(**Calendar**.DAY_OF_WEEK));

**Comment by YehorSurkov** [comment]
1 Вот такой вот я старомодный. Исправил. А  тут, или в другом месте я не захотел менять объект, поэтому написал:
Data mB = new GregorianCalendar(1994, sep ,27).getTime();
2 Исправил.
