### ISSUE TITLE
Товары

### ISSUE THREAD

**Issue by milkina** [YehorSurkov/homework#26]
1. Category - вместо  private ArrayList<Product> setOfProducts; 
лучше  private **List**<Product> setOfProducts; То же самое для параметров методов и конструкторов.
Имя тоже лучше просто products. 
2. Ex12, Ex5 - вместо
ArrayList<Product> arrClothes = new ArrayList<>()
лучше 
List<Product> arrClothes = new ArrayList<>()

**Comment by YehorSurkov** [comment]
Готово
