### ISSUE TITLE
MCalculator

### ISSUE THREAD

**Issue by milkina** [YehorSurkov/homework#6]
1.  addMatrixes, multMatrixRight - на вход передавайте объект класса MCalculator. Мы перешли к ООП и оперируем объектами.
2. addMatrixes, multToNumber, multMatrixRight - пусть возвращают объекты класса MCalculator, содержащие результат 
 вместо вывода на консоль. Метод showResult вызывайте отдельно из main. Так методы будут более универсальны.
3.  if ((callCount == m.length)) - лишняя пара скобок.
4. showResult - можно не передавать матрицу а выводить данные текущего объекта.
5. Конструктор лучше писать сразу после объявления переменных класса.

**Comment by YehorSurkov** [comment]
Думаю, тут стоило делать три класса: Matrix( private переменные int colCount, int rawCount и double[][] matrix), отдельно класс MCalculator с методами где, кстати, создать отдельные метод checkSize, чтоб не ретурнить непонятно что, и отдельно MCalculatorDemo. А то так всё ёще весьма накручено.

**Comment by YehorSurkov** [comment]
Так, вотя вообще не утверждаю, что всё ок. Но код я поправил.

**Comment by milkina** [comment]
1. переменные класса сделать private
2.  Метод showResult сделать НЕ статическим. Убрать параметры метода - используете this.

**Comment by YehorSurkov** [comment]
1) сделал. геттеры -сеттеры добавил.
2) Метод сделал не static.  
3) Использовал this для сложения и умножения на число. Хотя это же изменит сам объект, меня это с философской точки зрения не очень... Что если я дольше захочу его использовать таким, как я его задал? Т.е. не правильнее ли даже в ООП писать такие методы так, чтоб был  объекет1+объект2 = объект3, чтоб это и на уровне памяти, и на логическом были разные объекты.

 Собственно, из тех же соображений я делал showResult статичным, он же всеобщий и вообще не привязан ни к каким параметрам конкретной матрицы для которой он вызван (конкретной реализации класса), окромя той, что на входе. 

Либо делать что-то в стиле воид класса без ввода, но привязывать к переменной класса private double[][] matrix (так, мне кажется, будет идейно правильно, но это уже мелочи и частности):

В MCalculator: 
    public void showResult() {
        for (double[] raw : matrix) {
            for (double el : raw) {
                System.out.print(el + " ");
            }
            System.out.println();
        }
        System.out.println("\n"); 
    }

В MCalculatorDemo:
arr1.multMatrixRight(arr2);
arr1.showResult();

4) Для умножения справа this, строго говоря, вообще неприменим. Это - не групповая операция, на выходе мы не обязаны получить объект того же множества {матрицу той же размерности, что стоит слева (та, для которой метод вызван)}. E.g. M[3,3]*N[3,2]=G[3,2]; M[4,3]*N[3,2]=G[4,2] - строк столько, сколько в левой; столбцов столько, сколько в правой.

**Comment by YehorSurkov** [comment]
1) Класс MCalculator вернул практически к исходному самому первому варианту, с тем отличием что вместо массивов  - объекты MCalculator();

2) Добавил пакет mymatrixcalc. Моё видение реализации калькулятора, есть объект матрица с рядом атрибутов, и есть что-то Calculator, там где лежат методы, которые производятся не объектами, а над объектами, что позволяет, например, умножать не только справа без создания дополнительных объектов, или написать import. Класс, методы которого можно полностью финализировать. 

3) В уроке 4 ишью закрыт, а в таблице всё ещё нет.

**Comment by YehorSurkov** [comment]
По поводу длинных строк в идее, как и Spyder, MATlab, есть линия, которая (по крайней мере, в Spyder соответствует строго PEP8). Всё, что до неё, длинной строкой не является, это - место для полёта фантазии и обсфуркации:)
![image](https://user-images.githubusercontent.com/34401787/35513483-e82ae882-050b-11e8-82b7-4e9710067c88.png)
![image](https://user-images.githubusercontent.com/34401787/35513603-51ea4f92-050c-11e8-9eef-4480f2470bfc.png)
![image](https://user-images.githubusercontent.com/34401787/35513624-675393de-050c-11e8-892c-88c6975a6dd4.png)

**Comment by milkina** [comment]
2. Отлично, можно и так.
3. Закрыла

**Comment by milkina** [comment]
А у меня в идее не отображается этот разделитель. Не могу найти.
