### ISSUE TITLE
Phone

### ISSUE THREAD

**Issue by milkina** [YehorSurkov/homework#8]
1. Добавить мод. доступа конструкторам, стат. переменной, методам.
2. Класс тоже сделайте public
3. PhoneDemo - неотформатировано

**Comment by YehorSurkov** [comment]
1 Готово. Статическую сделал паблик только для того, чтоб вместо геттеров оставить её с PhoneDemo через точку. 
2 Готово
3 Готово. Как вы это замечаете? там же всего пару пробелов между плюсами появилось.

**Comment by milkina** [comment]
3.  Ха! Вы когда привыкните форматировать, тоже будете замечать.
