### ISSUE TITLE
Recursion

### ISSUE THREAD

**Issue by milkina** [YehorSurkov/homework#9]
1. Имена методов и переменных с маленькой буквы.
2. Это вы сами придумали  - (A + (B - A) / Math.abs(A - B), B)?

**Comment by YehorSurkov** [comment]
1 Готово.
2 Да. Работаю физиком в НИЧе Каразина. C лабами у нас не очень. Для работы на уровне "написать в американский журнал с импактом" приходится заниматься матфизикой, вычматом и компьютерным экспериментом. Как и в случае с 0! =1, я потратил время, чтоб не использовать никаких if. Опыта у меня всего  2 года, но случаев, когда я справлялся указать полную систему событий правильно (дефолт, вообще говоря, не приветствуется) в более-менее серьёзной симуляции или обработке, по пальцам одной руки сосчитать. Т.ч. я сразу пытаюсь избежать чрезмерного использования условий, хотя бы и в качестве тренировки. Да, переменные с большой буквы и разделение нижним подчёркиванием - оттуда же, ибо когда профессура была моложе дожди были дождее, коды кодее и использовалась такая вот, конечно же, единственно правильная форма записи, другая - вообще не признаётся...

**Comment by milkina** [comment]
1. Имена методов тоже с маленькой буквы.
2. Ну, это круто!  Вам надо устроиться на какой-то серьезный проект, будете незаменимым человеком.  В гугл очень любят принимать людей с такими знаниями, насколько я знаю. Промониторьте этот вопрос и готовьтесь к собеседованию заранее.

**Comment by YehorSurkov** [comment]
1 Готово.
